
[build]
    publish = "_site"
    functions = "functions/"

[dev]
    functions = "functions/"

[[headers]]
    for = "/media/*.pdf"
    [headers.values]
        Content-Disposition = "inline"
        Content-Type = "application/pdf"
